apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-web
spec:
  selector:
    matchLabels:
      app: myapp-web
  template:
    metadata:
      labels:
        app: myapp-web
    spec:
      containers:
      - name: node-app
        image: phiva1985/node:22.11.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
